spring:
    # 配置参考: CacheProperties.calss
    cache:
        type: simple

    # 配置参考: RedisProperties.class
    redis:
        database: 0
        host: localhost
        port: 6379
        password: root