# 由于Key 不能包含特殊字符,使用下面配置方式,mapping的key与allowedOrigins的key要对应

cors:
   allow-rule:
      mapping: 
         admin: '/admin/**'
         api: '/api/**'
      allowed-origins:
         admin:
            - 'http://192.18.1.12.3'
            - 'http://192.18.1.12.11'
         api:
            - '*'