spring:
    datasource:
        # 配置参考: HikariDataSource.class
        first:   #数据源1
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbcUrl: jdbc:mysql://localhost:3306/demo1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
            username: root
            password: root
        second:  #数据源2
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbcUrl: jdbc:mysql://localhost:3306/demo2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
            username: root
            password: root