spring:
    datasource:
        # 配置参考: HikariDataSource.class
        first:   #数据源1
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/demo1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
            username: root
            password: root
            # 可选配置
            initial-size: 0
            max-active: 20
            maxIdle: 20
            min-idle: 1
            max-wait: 60000
        second:  #数据源2
            driverClassName: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/demo2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
            username: root
            password: root
            # 可选配置
            initial-size: 0
            max-active: 20
            maxIdle: 20
            min-idle: 1
            max-wait: 60000

    # 配置参考: CacheProperties.calss
    cache:
        type: simple

    # 配置参考: RedisProperties.class
    redis:
        database: 0
        host: localhost
        port: 6379
        password: root