# 配置参考: ServerProperties.class
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000ms
    servlet:
      context-path: /demo

spring:
    # 环境 dev|prod
    profiles:
        active: dev
    # 配置参考: WebMvcProperties.class
    mvc:
        throw-exception-if-no-handler-found: true
        static-path-pattern: /static/**

# 静态资源路径
    resources:
        static-locations: classpath:static/

    # 配置参考: ThymeleafProperties.class
    thymeleaf:
       prefix: classpath:templates/
       suffix: .html
       encoding: UTF-8

    # 配置参考: MessageSourceProperties.class
    messages:
       # language文件夹下以messages开头的properties文件
       basename: language/messages
       encoding: UTF-8
       # 回滚到系统语言
       fallbackToSystemLocale: false

# 配置参考: MybatisProperties.class
mybatis:
   mapper-locations: classpath:mapper/**/*.xml

# log
logging:
   config: classpath:logback-spring.xml
   path: ./logs
