# 配置参考: ServerProperties.class
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000ms
    servlet:
      context-path: /

spring:
    # 环境 dev|prod
    profiles:
        active: dev
    # 配置参考: WebMvcProperties.class
    mvc:
       servlet:
          path: /demo
       throw-exception-if-no-handler-found: true
       static-path-pattern: /static/**

# 静态资源路径
    resources:
        static-locations: classpath:static/

    # 配置参考: ThymeleafProperties.class
    thymeleaf:
       prefix: classpath:templates/
       suffix: .html
       encoding: UTF-8

    # 配置参考: MessageSourceProperties.class
    messages:
       # language文件夹下以messages开头的properties文件
       basename: language/messages
       encoding: UTF-8
       # 回滚到系统语言
       fallbackToSystemLocale: false

# 配置参考: MybatisProperties.class
mybatis:
   # xml扫描路径
   mapper-locations: classpath:mapper/**/*.xml
   # 高级配置
   configuration:
      # 使用REUSE执行器,缓存sql编译后的statement
      default-executor-type: REUSE
      # 缓存
      cache-enabled: false
      # 下划线转驼峰
      map-underscore-to-camel-case: true

# 配置参照: PageHelperProperties.class
pagehelper:
   # pageSize =0 时,不分页
   page-size-zero: true
   # 参数合理化(pageNum<1会查询第一页,pageNum>pages会查询最后一页)
   reasonable: true
   # 使用RowBounds分页进行count查询
   row-bounds-with-count: false

# log
logging:
   config: classpath:logback-spring.xml
   path: ./logs

# 外部配置文件
location:
   # 数据源
   datasource: classpath:config/datasource-${spring.profiles.active}.yml
   # 缓存
   cache: classpath:config/cache-${spring.profiles.active}.yml
   # 跨域配置
   cors: classpath:config/cors-${spring.profiles.active}.yml
